### ISSUE TITLE
/editor support

### ISSUE THREAD

**Issue by Flamme13** [GeorgesAlkhouri/nvim-aider#2]
Hello! How to use /editor command for aider? It works but I can't save buffer with editor mode.

```
Error: E382: Cannot write, 'buftype' option is set
```

How to fix this problem or how to use it correctly in this plugin?

Thanks.

**Comment by GeorgesAlkhouri** [comment]
Hi, sorry for the late response. Maybe I dont get your question but using `/editor` command defeats the purpose of nvim-aider plugin. The plugin integrates aider directly into Neovim, so you don't need to open another Neovim instance.

**Comment by Flamme13** [comment]
Yes, you are right. But in default mode in vim it is better to work with text than in terminal mode. Maybe there is a solution for this. I would appreciate if you explain it to me.

**Comment by aweis89** [comment]
I've enabled this the flatten plugin https://github.com/aweis89/aider.nvim if you wanna check it out

**Comment by GeorgesAlkhouri** [comment]
Thanks for pointing that out. So I will close that issue bc I am not currently thinking about implementing this.
